### ISSUE TITLE
PullHook breaks page layout

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/react-onsenui#115]
__Environment__
Onsen 2 rc 17
React 0.7.5
All

__Encountered problem__
When a PullHook component is added to a page, it's content goes underneath the top toolbar.

__How to reproduce__
https://codepen.io/anon/pen/jAJGdx?editors=0011

**Comment by argelius** [comment]
Thank you @airamrguez !

**Comment by argelius** [comment]
This was fixed in a previous version. Forgot to close this issue.

**Comment by airamrguez** [comment]
@argelius If I'm not wrong this is still happening. I've updated the example with the latest releases to reproduce the error (OnsenUI 2.0.0 & react-onsenui 1.0.0). If you switch to the OnsenUI 2.0.0-rc.15 version then you'll see the example works even with the latest release of react-onsenui.

http://codepen.io/airamrguez/pen/QKEjdq?editors=1010

**Comment by argelius** [comment]
@airamrguez Are you sure?

http://codepen.io/argelius/pen/amkvyr

For me it works fine. What browser are you using?

**Comment by airamrguez** [comment]
@argelius I'm using the latest Chrome version. The link above has wrong library versions because I were playing to see which version worked.

Now its pointing to the latest onsen releases:

http://codepen.io/airamrguez/pen/QKEjdq?editors=1010

**Comment by argelius** [comment]
@airamrguez You only updated the JS library, there were a couple of changes in the CSS of the pull hook also lately.

**Comment by airamrguez** [comment]
@argelius Good catch!!! I totally forgot about updating the css. I've tested it now with the new css and it's working fine!

Thank you so much!! You're doing a really great work.
